apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/naveenkumarsp/gitops-k8sbootstrap.git
    targetRevision: HEAD
    path: "devopstools/jenkins"

    # helm specific config
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      repoURL: https://github.com/helm/charts
      chart: "stable/jenkins"
      # Release name override (defaults to application name)
      releaseName: jenkins
      valueFiles:
      - jenkins-values.yaml

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
